language: python

addons:
  apt:
    packages:
      - gfortran  # scipy
      - libblas-dev  # scipy
      - liblapack-dev  # scipy
      - python-m2crypto  # glue

matrix:
  include:
    - python: 2.6
      env: PRE=""
    - python: 2.7
      env: PRE=""
    - python: 2.7
      env: PRE="--pre"
  allow_failures:
    - python: 2.7
      env: PRE="--pre"

before_install:
  - pip install -q --upgrade pip

install:
  - pip install ${PRE} -r requirements.txt

script:
  - pip install .

cache:
  apt: true
  pip: true
